language: rust

dist: xenial

addons:
  apt:
    packages:
     - golang-go
     - libev-dev
     - uthash-dev

matrix:
  include:
   - rust: stable
     install:
      - rustup component add clippy
     script:
      - cargo build --verbose --all
      - cargo test --verbose --all
      - cargo clippy --all --examples -- -D warnings
      - cargo doc --no-deps
      - make -C examples
   - rust: beta
     script:
      - cargo build --verbose --all
      - cargo test --verbose --all
      - cargo doc --no-deps
      - make -C examples
   - rust: nightly
     install:
      - rustup component add rustfmt
     script:
      - cargo build --verbose --all
      - cargo test --verbose --all
      - cargo fmt -- --check
      - cargo doc --no-deps
      - make -C examples

deploy:
  provider: pages
  fqdn: docs.quic.tech
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
