language: rust

dist: xenial

rust:
 - stable
 - beta
 - nightly

addons:
  apt:
    packages:
     - cmake
     - golang-go

script:
 - cargo build --verbose --all --examples
 - cargo test --verbose --all
