language: rust

dist: xenial

rust:
 - stable
 - beta
 - nightly

addons:
  apt:
    packages:
     - golang-go
     - libev-dev
     - uthash-dev

before_script:
 - rustup component add clippy

script:
 - cargo build --verbose --all --all-features --all-targets
 - cargo test --verbose --all --all-features --all-targets
 - cargo clippy --verbose --all --all-features -- -D warnings
 - cargo doc --no-deps
 - make -C examples

deploy:
  provider: pages
  fqdn: docs.quic.tech
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
