language: rust

rust:
 - stable
 - beta
 - nightly

install:
 - sudo apt-get update
 - sudo apt-get install cmake golang-go

script:
 - cargo build --verbose --all --examples
 - cargo test --verbose --all
