[package]
name = "quiche"
version = "0.1.0"
authors = ["Alessandro Ghedini <alessandro@ghedini.me>"]
edition = "2018"
build = "src/build.rs"

[build-dependencies]
cmake = "0"

[dependencies]
log = "0"
libc = "0"
ring = { git = "https://github.com/ghedo/ring", branch = "unauthenticated_stream_aes" }
lazy_static = "1"

[dev-dependencies]
mio = "0"
url = "1"
docopt = "1"
env_logger = "0"

[lib]
crate-type = ["lib", "staticlib"]
